### ISSUE TITLE
Issue with new version of Typescript 2.1.4

### ISSUE THREAD

**Issue by AlexRex** [Teradata/covalent-quickstart#23]
This repository's issues are reserved for feature requests and bug reports.

#### Bug Report

As the package.json has all the dependencies written with `^`, npm is installling typescript version 2.1.4 and this version breaks something in the build process (https://github.com/s-panferov/awesome-typescript-loader/issues/190#issuecomment-263435110).

##### Screenshots or link to CodePen/Plunker/JSfiddle
```bash
$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
** NG Live Development Server is running on http://localhost:4200. **
 11% building modules 9/18 modules 9 active ...s/webpack-dev-server/client/socket.jsTypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
    at /Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:228:3
    at Object.context.callback (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/angular2-template-loader/index.js:32:10)
    at LOADER_EXECUTION (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at /Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/instance.ts:266:72)\n    at Object.ensureInstance (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/instance.ts:145:5)\n    at compiler (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at iterateNormalLoaders (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:213:10)\n    at /Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:228:3\n    at Object.context.callback (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:106:13)\n    at Object.module.exports (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/angular2-template-loader/index.js:32:10)\n    at LOADER_EXECUTION (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)'
3544ms building modules    1ms add1m309ms c32ms asset15ms emittinggHash: 74b3a6409ee63f01d662
Version: webpack 2.1.0-beta.25
Time: 3980ms
                                 Asset       Size  Chunks             Chunk Names
                     scripts.bundle.js    97.5 kB    2, 3  [emitted]  scripts
  e79bfd88537def476913f3ed52f4f4b3.eot     143 kB          [emitted]
 012cf6a10129e2275d79d6adac7f3b02.woff    57.6 kB          [emitted]
570eb83859dc23dd0eec423a49e147fe.woff2    44.3 kB          [emitted]
                        main.bundle.js     241 kB    0, 3  [emitted]  main
                      styles.bundle.js     354 kB    1, 3  [emitted]  styles
  a37b0c01c0baf1888ca812cc0508f6e2.ttf     128 kB          [emitted]
                             inline.js    5.53 kB       3  [emitted]  inline
                              main.map     299 kB    0, 3  [emitted]  main
                            styles.map     473 kB    1, 3  [emitted]  styles
                           scripts.map     119 kB    2, 3  [emitted]  scripts
                            inline.map    5.59 kB       3  [emitted]  inline
                            index.html  694 bytes          [emitted]

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/aletormat/Dev/githubRubbish/covalent-quickstart/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.97 kB       0
webpack: bundle is now VALID.
```

##### Other information

After changing the package.json and install typescript 2.0.10 fixes the problem. 
`"typescript": "2.0.10"`. I would suggest to don't declare the versions with `^` in the package.json.

**Comment by emoralesb05** [comment]
Awesome, thanks for checking. We noticed this in our internal products, we just forgot to update the quickstart haha 😄
